version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-31
    environment:
      # Setup your environment variables here if needed
    steps:
      - checkout

      # Cài đặt Flutter SDK
      - run:
          name: Install Flutter SDK
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends \
              apt-transport-https \
              ca-certificates \
              gnupg \
              curl \
              git \
              unzip \
              xz-utils \
            && sudo rm -rf /var/lib/apt/lists/*
            sudo curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.10.0-stable.tar.xz -o flutter.tar.xz
            sudo tar xf flutter.tar.xz -C /home/circleci
            export PATH="$PATH:/home/circleci/flutter/bin"

      # Cài đặt các phụ thuộc của ứng dụng Flutter
      - run:
          name: Install Flutter dependencies
          command: flutter pub get

      # Cài đặt lại các thư viện của iOS bằng CocoaPods
      - run:
          name: Install CocoaPods dependencies
          command: |
            sudo gem install cocoapods
            cd ios
            pod install
            cd ..

      # Thực hiện quy trình build cho iOS
      - run:
          name: Build iOS app
          command: flutter build ios --release --no-codesign

workflows:
  version: 2
  build:
    jobs:
      - build
