// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD9VTOx2VwPVPkB5mNhQi7mW1DsSWPFuvQ',
//     appId: '1:331786127189:web:fc60c56e55a5c3c4d011dc',
//     messagingSenderId: '331786127189',
//     projectId: 'tmart-753e5',
//     authDomain: 'tmart-753e5.firebaseapp.com',
//     storageBucket: 'tmart-753e5.appspot.com',
//     measurementId: 'G-EB0HW0XY3Q',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA9eMsO5GWVdyiNibMhlqpAGrAgmDdv8F4',
//     appId: '1:331786127189:android:682fa8ed57cbf12dd011dc',
//     messagingSenderId: '331786127189',
//     projectId: 'tmart-753e5',
//     storageBucket: 'tmart-753e5.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAoN8eaBweNPPBX9gWAmO2vjNp9f2Gtoa8',
//     appId: '1:331786127189:ios:85edf171256f74fbd011dc',
//     messagingSenderId: '331786127189',
//     projectId: 'tmart-753e5',
//     storageBucket: 'tmart-753e5.appspot.com',
//     iosBundleId: 'com.example.appFtTmart',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAoN8eaBweNPPBX9gWAmO2vjNp9f2Gtoa8',
//     appId: '1:331786127189:ios:85edf171256f74fbd011dc',
//     messagingSenderId: '331786127189',
//     projectId: 'tmart-753e5',
//     storageBucket: 'tmart-753e5.appspot.com',
//     iosBundleId: 'com.example.appFtTmart',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD9VTOx2VwPVPkB5mNhQi7mW1DsSWPFuvQ',
//     appId: '1:331786127189:web:81527f65938093c1d011dc',
//     messagingSenderId: '331786127189',
//     projectId: 'tmart-753e5',
//     authDomain: 'tmart-753e5.firebaseapp.com',
//     storageBucket: 'tmart-753e5.appspot.com',
//     measurementId: 'G-SS70R0MP27',
//   );

// }