// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlt2MAcBj30uVc9-s4-trVtc22ea9kq84',
    appId: '1:832314608375:web:d7bf90071124ce3d1aa1f2',
    messagingSenderId: '832314608375',
    projectId: 'tmart-119c0',
    authDomain: 'tmart-119c0.firebaseapp.com',
    storageBucket: 'tmart-119c0.appspot.com',
    measurementId: 'G-Q24RV139EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG7vwRPAmpo_6JFWqGsgJiV0w8rt_XFMY',
    appId: '1:832314608375:android:407997c1289de2621aa1f2',
    messagingSenderId: '832314608375',
    projectId: 'tmart-119c0',
    storageBucket: 'tmart-119c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSlGIHodnTyt54SDZVx7IJkjz38zk3gCY',
    appId: '1:832314608375:ios:e4d8b78c6f9aa8501aa1f2',
    messagingSenderId: '832314608375',
    projectId: 'tmart-119c0',
    storageBucket: 'tmart-119c0.appspot.com',
    iosBundleId: 'com.example.appFtTmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSlGIHodnTyt54SDZVx7IJkjz38zk3gCY',
    appId: '1:832314608375:ios:0a7ec4dbb505d4661aa1f2',
    messagingSenderId: '832314608375',
    projectId: 'tmart-119c0',
    storageBucket: 'tmart-119c0.appspot.com',
    iosBundleId: 'com.example.appFtTmart.RunnerTests',
  );
}
